version: "3.9"
name: "Diploma"

services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: >
      redis-server --appendonly yes --requirepass pass
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "pass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


  gui_service:
    container_name: gui_service
    build:
      context: .
      dockerfile: gui_service/gui_service.dockerfile
    ports:
      - "8083:8083"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT_FAST_API: 8083
      HOST_FAST_API: "0.0.0.0"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  raspberry_service:
    container_name: raspberry_service
    build:
      context: .
      dockerfile: raspberry_service/rustberi_service.dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      PORT_FAST_API: 8082
      HOST_FAST_API: "0.0.0.0"
      BOOTSTRAP_SERVER: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  raspberry-pi1:
    container_name: rp1
    depends_on:
      raspberry_service:
        condition: service_healthy
    build:
      context: .
      dockerfile: rustberi_emulator/emulate.dockerfile
    environment:
      SERVER_URL: "http://raspberry_service:8082"
      DEVICE_ID: "mai-1"
      LAT: "55.46"
      LON: "37.37"
  raspberry-pi2:
    container_name: rp2
    depends_on:
      raspberry_service:
        condition: service_healthy
    build:
      context: .
      dockerfile: rustberi_emulator/emulate.dockerfile
    environment:
      SERVER_URL: "http://raspberry_service:8082"
      DEVICE_ID: "mai-2"
      LAT: "56.46"
      LON: "37.37"

volumes:
  redis_data:
  clickhouse_data: