version: "3.9"
name: "Diploma"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass pass

volumes:
  redis_data: